# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/fss/mjj/markdown_module

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/fss/mjj/markdown_module

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/fss/mjj/markdown_module/CMakeFiles /Users/fss/mjj/markdown_module/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/fss/mjj/markdown_module/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/build
.PHONY : parser/fast

markdown_src/main.o: markdown_src/main.c.o

.PHONY : markdown_src/main.o

# target to build an object file
markdown_src/main.c.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/main.c.o
.PHONY : markdown_src/main.c.o

markdown_src/main.i: markdown_src/main.c.i

.PHONY : markdown_src/main.i

# target to preprocess a source file
markdown_src/main.c.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/main.c.i
.PHONY : markdown_src/main.c.i

markdown_src/main.s: markdown_src/main.c.s

.PHONY : markdown_src/main.s

# target to generate assembly for a file
markdown_src/main.c.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/main.c.s
.PHONY : markdown_src/main.c.s

markdown_src/markdown_convert/markdown_html2pdf.o: markdown_src/markdown_convert/markdown_html2pdf.c.o

.PHONY : markdown_src/markdown_convert/markdown_html2pdf.o

# target to build an object file
markdown_src/markdown_convert/markdown_html2pdf.c.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_convert/markdown_html2pdf.c.o
.PHONY : markdown_src/markdown_convert/markdown_html2pdf.c.o

markdown_src/markdown_convert/markdown_html2pdf.i: markdown_src/markdown_convert/markdown_html2pdf.c.i

.PHONY : markdown_src/markdown_convert/markdown_html2pdf.i

# target to preprocess a source file
markdown_src/markdown_convert/markdown_html2pdf.c.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_convert/markdown_html2pdf.c.i
.PHONY : markdown_src/markdown_convert/markdown_html2pdf.c.i

markdown_src/markdown_convert/markdown_html2pdf.s: markdown_src/markdown_convert/markdown_html2pdf.c.s

.PHONY : markdown_src/markdown_convert/markdown_html2pdf.s

# target to generate assembly for a file
markdown_src/markdown_convert/markdown_html2pdf.c.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_convert/markdown_html2pdf.c.s
.PHONY : markdown_src/markdown_convert/markdown_html2pdf.c.s

markdown_src/markdown_convert/markdown_time.o: markdown_src/markdown_convert/markdown_time.c.o

.PHONY : markdown_src/markdown_convert/markdown_time.o

# target to build an object file
markdown_src/markdown_convert/markdown_time.c.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_convert/markdown_time.c.o
.PHONY : markdown_src/markdown_convert/markdown_time.c.o

markdown_src/markdown_convert/markdown_time.i: markdown_src/markdown_convert/markdown_time.c.i

.PHONY : markdown_src/markdown_convert/markdown_time.i

# target to preprocess a source file
markdown_src/markdown_convert/markdown_time.c.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_convert/markdown_time.c.i
.PHONY : markdown_src/markdown_convert/markdown_time.c.i

markdown_src/markdown_convert/markdown_time.s: markdown_src/markdown_convert/markdown_time.c.s

.PHONY : markdown_src/markdown_convert/markdown_time.s

# target to generate assembly for a file
markdown_src/markdown_convert/markdown_time.c.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_convert/markdown_time.c.s
.PHONY : markdown_src/markdown_convert/markdown_time.c.s

markdown_src/markdown_convert/markdown_tohtml.o: markdown_src/markdown_convert/markdown_tohtml.c.o

.PHONY : markdown_src/markdown_convert/markdown_tohtml.o

# target to build an object file
markdown_src/markdown_convert/markdown_tohtml.c.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_convert/markdown_tohtml.c.o
.PHONY : markdown_src/markdown_convert/markdown_tohtml.c.o

markdown_src/markdown_convert/markdown_tohtml.i: markdown_src/markdown_convert/markdown_tohtml.c.i

.PHONY : markdown_src/markdown_convert/markdown_tohtml.i

# target to preprocess a source file
markdown_src/markdown_convert/markdown_tohtml.c.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_convert/markdown_tohtml.c.i
.PHONY : markdown_src/markdown_convert/markdown_tohtml.c.i

markdown_src/markdown_convert/markdown_tohtml.s: markdown_src/markdown_convert/markdown_tohtml.c.s

.PHONY : markdown_src/markdown_convert/markdown_tohtml.s

# target to generate assembly for a file
markdown_src/markdown_convert/markdown_tohtml.c.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_convert/markdown_tohtml.c.s
.PHONY : markdown_src/markdown_convert/markdown_tohtml.c.s

markdown_src/markdown_parser/markdown_paragraph.o: markdown_src/markdown_parser/markdown_paragraph.c.o

.PHONY : markdown_src/markdown_parser/markdown_paragraph.o

# target to build an object file
markdown_src/markdown_parser/markdown_paragraph.c.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_parser/markdown_paragraph.c.o
.PHONY : markdown_src/markdown_parser/markdown_paragraph.c.o

markdown_src/markdown_parser/markdown_paragraph.i: markdown_src/markdown_parser/markdown_paragraph.c.i

.PHONY : markdown_src/markdown_parser/markdown_paragraph.i

# target to preprocess a source file
markdown_src/markdown_parser/markdown_paragraph.c.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_parser/markdown_paragraph.c.i
.PHONY : markdown_src/markdown_parser/markdown_paragraph.c.i

markdown_src/markdown_parser/markdown_paragraph.s: markdown_src/markdown_parser/markdown_paragraph.c.s

.PHONY : markdown_src/markdown_parser/markdown_paragraph.s

# target to generate assembly for a file
markdown_src/markdown_parser/markdown_paragraph.c.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_parser/markdown_paragraph.c.s
.PHONY : markdown_src/markdown_parser/markdown_paragraph.c.s

markdown_src/markdown_parser/markdown_parser.o: markdown_src/markdown_parser/markdown_parser.c.o

.PHONY : markdown_src/markdown_parser/markdown_parser.o

# target to build an object file
markdown_src/markdown_parser/markdown_parser.c.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_parser/markdown_parser.c.o
.PHONY : markdown_src/markdown_parser/markdown_parser.c.o

markdown_src/markdown_parser/markdown_parser.i: markdown_src/markdown_parser/markdown_parser.c.i

.PHONY : markdown_src/markdown_parser/markdown_parser.i

# target to preprocess a source file
markdown_src/markdown_parser/markdown_parser.c.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_parser/markdown_parser.c.i
.PHONY : markdown_src/markdown_parser/markdown_parser.c.i

markdown_src/markdown_parser/markdown_parser.s: markdown_src/markdown_parser/markdown_parser.c.s

.PHONY : markdown_src/markdown_parser/markdown_parser.s

# target to generate assembly for a file
markdown_src/markdown_parser/markdown_parser.c.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_parser/markdown_parser.c.s
.PHONY : markdown_src/markdown_parser/markdown_parser.c.s

markdown_src/markdown_parser/markdown_sentence.o: markdown_src/markdown_parser/markdown_sentence.c.o

.PHONY : markdown_src/markdown_parser/markdown_sentence.o

# target to build an object file
markdown_src/markdown_parser/markdown_sentence.c.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_parser/markdown_sentence.c.o
.PHONY : markdown_src/markdown_parser/markdown_sentence.c.o

markdown_src/markdown_parser/markdown_sentence.i: markdown_src/markdown_parser/markdown_sentence.c.i

.PHONY : markdown_src/markdown_parser/markdown_sentence.i

# target to preprocess a source file
markdown_src/markdown_parser/markdown_sentence.c.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_parser/markdown_sentence.c.i
.PHONY : markdown_src/markdown_parser/markdown_sentence.c.i

markdown_src/markdown_parser/markdown_sentence.s: markdown_src/markdown_parser/markdown_sentence.c.s

.PHONY : markdown_src/markdown_parser/markdown_sentence.s

# target to generate assembly for a file
markdown_src/markdown_parser/markdown_sentence.c.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_parser/markdown_sentence.c.s
.PHONY : markdown_src/markdown_parser/markdown_sentence.c.s

markdown_src/markdown_token/markdown_headnodes.o: markdown_src/markdown_token/markdown_headnodes.c.o

.PHONY : markdown_src/markdown_token/markdown_headnodes.o

# target to build an object file
markdown_src/markdown_token/markdown_headnodes.c.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_token/markdown_headnodes.c.o
.PHONY : markdown_src/markdown_token/markdown_headnodes.c.o

markdown_src/markdown_token/markdown_headnodes.i: markdown_src/markdown_token/markdown_headnodes.c.i

.PHONY : markdown_src/markdown_token/markdown_headnodes.i

# target to preprocess a source file
markdown_src/markdown_token/markdown_headnodes.c.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_token/markdown_headnodes.c.i
.PHONY : markdown_src/markdown_token/markdown_headnodes.c.i

markdown_src/markdown_token/markdown_headnodes.s: markdown_src/markdown_token/markdown_headnodes.c.s

.PHONY : markdown_src/markdown_token/markdown_headnodes.s

# target to generate assembly for a file
markdown_src/markdown_token/markdown_headnodes.c.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_token/markdown_headnodes.c.s
.PHONY : markdown_src/markdown_token/markdown_headnodes.c.s

markdown_src/markdown_token/markdown_token.o: markdown_src/markdown_token/markdown_token.c.o

.PHONY : markdown_src/markdown_token/markdown_token.o

# target to build an object file
markdown_src/markdown_token/markdown_token.c.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_token/markdown_token.c.o
.PHONY : markdown_src/markdown_token/markdown_token.c.o

markdown_src/markdown_token/markdown_token.i: markdown_src/markdown_token/markdown_token.c.i

.PHONY : markdown_src/markdown_token/markdown_token.i

# target to preprocess a source file
markdown_src/markdown_token/markdown_token.c.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_token/markdown_token.c.i
.PHONY : markdown_src/markdown_token/markdown_token.c.i

markdown_src/markdown_token/markdown_token.s: markdown_src/markdown_token/markdown_token.c.s

.PHONY : markdown_src/markdown_token/markdown_token.s

# target to generate assembly for a file
markdown_src/markdown_token/markdown_token.c.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_token/markdown_token.c.s
.PHONY : markdown_src/markdown_token/markdown_token.c.s

markdown_src/markdown_translate/cJSON.o: markdown_src/markdown_translate/cJSON.c.o

.PHONY : markdown_src/markdown_translate/cJSON.o

# target to build an object file
markdown_src/markdown_translate/cJSON.c.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_translate/cJSON.c.o
.PHONY : markdown_src/markdown_translate/cJSON.c.o

markdown_src/markdown_translate/cJSON.i: markdown_src/markdown_translate/cJSON.c.i

.PHONY : markdown_src/markdown_translate/cJSON.i

# target to preprocess a source file
markdown_src/markdown_translate/cJSON.c.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_translate/cJSON.c.i
.PHONY : markdown_src/markdown_translate/cJSON.c.i

markdown_src/markdown_translate/cJSON.s: markdown_src/markdown_translate/cJSON.c.s

.PHONY : markdown_src/markdown_translate/cJSON.s

# target to generate assembly for a file
markdown_src/markdown_translate/cJSON.c.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_translate/cJSON.c.s
.PHONY : markdown_src/markdown_translate/cJSON.c.s

markdown_src/markdown_translate/markdown_translate.o: markdown_src/markdown_translate/markdown_translate.c.o

.PHONY : markdown_src/markdown_translate/markdown_translate.o

# target to build an object file
markdown_src/markdown_translate/markdown_translate.c.o:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_translate/markdown_translate.c.o
.PHONY : markdown_src/markdown_translate/markdown_translate.c.o

markdown_src/markdown_translate/markdown_translate.i: markdown_src/markdown_translate/markdown_translate.c.i

.PHONY : markdown_src/markdown_translate/markdown_translate.i

# target to preprocess a source file
markdown_src/markdown_translate/markdown_translate.c.i:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_translate/markdown_translate.c.i
.PHONY : markdown_src/markdown_translate/markdown_translate.c.i

markdown_src/markdown_translate/markdown_translate.s: markdown_src/markdown_translate/markdown_translate.c.s

.PHONY : markdown_src/markdown_translate/markdown_translate.s

# target to generate assembly for a file
markdown_src/markdown_translate/markdown_translate.c.s:
	$(MAKE) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/markdown_src/markdown_translate/markdown_translate.c.s
.PHONY : markdown_src/markdown_translate/markdown_translate.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... parser"
	@echo "... markdown_src/main.o"
	@echo "... markdown_src/main.i"
	@echo "... markdown_src/main.s"
	@echo "... markdown_src/markdown_convert/markdown_html2pdf.o"
	@echo "... markdown_src/markdown_convert/markdown_html2pdf.i"
	@echo "... markdown_src/markdown_convert/markdown_html2pdf.s"
	@echo "... markdown_src/markdown_convert/markdown_time.o"
	@echo "... markdown_src/markdown_convert/markdown_time.i"
	@echo "... markdown_src/markdown_convert/markdown_time.s"
	@echo "... markdown_src/markdown_convert/markdown_tohtml.o"
	@echo "... markdown_src/markdown_convert/markdown_tohtml.i"
	@echo "... markdown_src/markdown_convert/markdown_tohtml.s"
	@echo "... markdown_src/markdown_parser/markdown_paragraph.o"
	@echo "... markdown_src/markdown_parser/markdown_paragraph.i"
	@echo "... markdown_src/markdown_parser/markdown_paragraph.s"
	@echo "... markdown_src/markdown_parser/markdown_parser.o"
	@echo "... markdown_src/markdown_parser/markdown_parser.i"
	@echo "... markdown_src/markdown_parser/markdown_parser.s"
	@echo "... markdown_src/markdown_parser/markdown_sentence.o"
	@echo "... markdown_src/markdown_parser/markdown_sentence.i"
	@echo "... markdown_src/markdown_parser/markdown_sentence.s"
	@echo "... markdown_src/markdown_token/markdown_headnodes.o"
	@echo "... markdown_src/markdown_token/markdown_headnodes.i"
	@echo "... markdown_src/markdown_token/markdown_headnodes.s"
	@echo "... markdown_src/markdown_token/markdown_token.o"
	@echo "... markdown_src/markdown_token/markdown_token.i"
	@echo "... markdown_src/markdown_token/markdown_token.s"
	@echo "... markdown_src/markdown_translate/cJSON.o"
	@echo "... markdown_src/markdown_translate/cJSON.i"
	@echo "... markdown_src/markdown_translate/cJSON.s"
	@echo "... markdown_src/markdown_translate/markdown_translate.o"
	@echo "... markdown_src/markdown_translate/markdown_translate.i"
	@echo "... markdown_src/markdown_translate/markdown_translate.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

